version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-snapstart-trial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iul6sxg0y9wf"
s3_prefix = "aws-lambda-snapstart-trial"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
